# Generated by Django 2.2 on 2019-04-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20190418_0524'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='Cities2',
        ),
    ]
